spring:
  application:
    name: eureka-service-discovery
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

## para que o projeto seja apenas servidor e não cliente
## deve-se colocar essas duas confis
