server:
  port: 8092
  error:
    include-message: always

# datasource
spring:
  application:
    name: employee-api
  config:
    import: optional:configserver:http://localhost:8080

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true
