spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/employee?useTimezone=true&serverTimezone=UTC
    username: root
    password: pass
  sql:
    init:
      mode: always
